### ISSUE TITLE
Paris 2024 ?

### ISSUE THREAD

**Issue by hugolpz** [chanronnie/Olympics#1]
You may have better sources hopefully. 
Else this one seems complete https://olympics.com/en/paris-2024/athletes : 222 pages x 50 athletes = 11065 athletes.

**Comment by chanronnie** [comment]
Thanks for the suggestion😊! My project focuses on Olympian data from 1896 to 2022, so I’m not planning to include the 2024 data (as the 2024 Olympics are still ongoing as of August 8, 2024). The link you shared is great for anyone interested in the latest info, though! I'll close this issue for now. I appreciate your understanding, and any other questions are welcome.

**Comment by hugolpz** [comment]
Perfect :)
You have the information so you can do informed decision.

Note: in the meanwhile, I downloaded some of their code data, see https://github.com/hugolpz/Paris2024 . But I don't know the Licence status of those data.
